### ISSUE TITLE
Activity annotation name

### ISSUE THREAD

**Issue by rafakob** [kobakei/iberico#10]
Have you considering changing `@Launcher` name to something else? IMO, "Launcher" is more associated with android launcher application.

Maybe something like `@ActivityWithExtras`? Would suit well with [FragmentArgs](https://github.com/sockeqwe/fragmentargs).

Anyway, nice work here. Library is so simple, yet do the job.

**Comment by kobakei** [comment]
`@Launcher` annotation can be set to not only activity but also service and broadcastreceivers.
Do you have any good idea?

**Comment by kobakei** [comment]
Renamed to `@Navigator`.
