### ISSUE TITLE
Replace @Nullable with annotation value

### ISSUE THREAD

**Issue by rafakob** [kobakei/iberico#11]
Using `@Nullable` to indicate that a field is optional is just not right. I know that Dart is doing this, but I think better option is simple annotation value:
`@Extras(required = false)` like in [FragmentArge](https://github.com/sockeqwe/fragmentargs/blob/master/annotation/src/main/java/com/hannesdorfmann/fragmentargs/annotation/Arg.java)

**Comment by kobakei** [comment]
Thanks for your feedback.
Annotation about optional params will be updated at next release .

**Comment by kobakei** [comment]
Needs `@Optional` on 0.2.0
