### ISSUE TITLE
inject() method

### ISSUE THREAD

**Issue by rafakob** [kobakei/iberico#9]
Hello,
Why not change 
`DetailActivityIntentBuilder.inject(this, getIntent());` 
to 
`DetailActivityIntentBuilder.inject(this);`
and insde generated method just call `target.getIntent()`.

**Comment by kobakei** [comment]
`getIntent()` is available only for activity, not service and broadcastreceiver.
Therefore `inject` needs Intent arg.

**Comment by rafakob** [comment]
You could add second method:

``` java
  public static void inject(MainActivity target) {
        inject(target, target.getIntent());
  }

  public static void inject(MainActivity target, Intent intent) {
    target.test = Parcels.unwrap(intent.getParcelableExtra("test"));
  }
```

I know that those are just details, but it looks nicer that way :P
